image: gitpod/workspace-full

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install awscli -y
      exit
  - command: docker

vscode:
  extensions:
    - ms-azuretools.vscode-docker

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
